allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
  sharp: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
onlyBuiltDependencies:
  - esbuild
packages:
  - 'apps/playground'
