allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
  sharp: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
minimumReleaseAgeExclude:
  - '@spartan-ng/brain@0.0.1-alpha.710'
  - '@spartan-ng/cli@0.0.1-alpha.710'
onlyBuiltDependencies:
  - esbuild
packages:
  - 'apps/playground'
