name: release dfx-openapi

on:
  push:
    tags:
      - 'dfx-openapi**'

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for GitHub release action

jobs:
  dfx-openapi:
    uses: ./.github/workflows/release.yml
    with:
      lib: dfx-openapi
