name: release dfx-qrcode

on:
  push:
    tags:
      - 'dfx-qrcode**'

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for GitHub release action

jobs:
  dfx-qrcode:
    uses: ./.github/workflows/release.yml
    with:
      lib: dfx-qrcode
