name: release dfx-helper

on:
  push:
    tags:
      - 'dfx-helper**'

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for GitHub release action

jobs:
  dfx-helper:
    uses: ./.github/workflows/release.yml
    with:
      lib: dfx-helper
