name: release dfx-transloco-markup

on:
  push:
    tags:
      - 'dfx-transloco-markup**'

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for GitHub release action

jobs:
  dfx-transloco-markup:
    uses: ./.github/workflows/release.yml
    with:
      lib: dfx-transloco-markup
